#!/usr/bin/env python3
"""Generate bilingual README files from prompts.json.

Single source of truth: ../prompts.json. Standard library only. Run via:

    python scripts/build_readmes.py

This repo opens as a curated home for Seedance 2.5 video prompts. Until the
model is publicly available (early July 2026), the entries are author-built
*starter templates* that demonstrate prompt structure; community-contributed,
output-verified prompts are added as the model ships.
"""
from __future__ import annotations

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "prompts.json"

REPO_URL = "https://github.com/ToseaAI/awesome-seedance-2.5-prompts"
TOSEA_PROMPTS_URL = "https://tosea.ai/prompts/seedance-2-5"
TOSEA_HOME_URL = "https://tosea.ai"
BLOG_URL = "https://tosea.ai/blog/seedance-2-5-bytedance-ai-video-model-guide"

CATEGORY_ORDER = [
    "text-to-video",
    "image-to-video",
    "multi-reference",
    "region-edit",
    "camera-cinematic",
]

CATEGORY_LABELS = {
    "en": {
        "text-to-video": "Text-to-Video",
        "image-to-video": "Image-to-Video",
        "multi-reference": "Multi-Reference Consistency",
        "region-edit": "Region Editing",
        "camera-cinematic": "Camera & Cinematic",
    },
    "zh": {
        "text-to-video": "文生视频",
        "image-to-video": "图生视频",
        "multi-reference": "多参考一致性",
        "region-edit": "局部编辑",
        "camera-cinematic": "运镜与电影感",
    },
}

STR = {
    "en": {
        "lang_attr": "en",
        "tagline": "Direct 30-second clips. 50 multimodal references. Region-level control.",
        "lang_self": "English",
        "lang_alt": "中文",
        "lang_alt_href": "README.zh-CN.md",
        "intro": (
            "A curated, open-source collection of prompts for **ByteDance's "
            "Seedance 2.5** — the Doubao video generation model previewed at the "
            "Volcano Engine FORCE conference on **June 23, 2026**, with a public "
            "launch set for **early July 2026**. Prompts are organized by use "
            "case: text-to-video, image-to-video, multi-reference consistency, "
            "region editing, and camera work."
        ),
        "status_head": "Status",
        "status_body": (
            "Seedance 2.5 is in preview (enterprise beta) and is **not yet "
            "publicly available**. This repository is opening early so the "
            "community has a home for Seedance 2.5 prompts the day the model "
            "ships. The entries below are author-built **starter templates** "
            "that demonstrate effective prompt structure — they are clearly "
            "labelled, carry no fabricated outputs, and will be joined by "
            "community-contributed, output-verified prompts as the public model "
            "rolls out. Want to help seed it? See [Contributing](#contributing)."
        ),
        "about_head": "What Is Seedance 2.5?",
        "about_body": (
            "Seedance 2.5 is ByteDance's next-generation video model. Per the "
            "FORCE keynote, its three headline upgrades are:\n\n"
            "- **30-second single clips** — one continuous take, generated "
            "directly (up from 15s in Seedance 2.0), so narratives hold without "
            "stitching.\n"
            "- **Up to 50 multimodal references** — images, video, and text "
            "combined in one joint generation (up from 12), for cross-shot "
            "character and brand consistency.\n"
            "- **More controllable editing** — region-level edits (swap a "
            "subject without changing the motion, camera, or lighting) plus a 3D "
            "white-model previsualization step.\n\n"
            f"For the full breakdown and how it compares, read our [Seedance 2.5 "
            f"guide]({BLOG_URL})."
        ),
        "toc_head": "Contents",
        "contributing_head": "Contributing",
        "contributing_body": (
            "We welcome prompt contributions. **Only edit `prompts.json`** — the "
            "READMEs are auto-generated by `scripts/build_readmes.py` and will be "
            "overwritten on merge. Once the public model ships, attach the output "
            "video/GIF and credit the prompt's author. See "
            "[CONTRIBUTING.md](CONTRIBUTING.md) for the schema."
        ),
        "license_head": "License",
        "license_body": (
            "This collection is released under [CC BY 4.0](LICENSE). Individual "
            "prompts remain the intellectual property of their authors; we curate, "
            "translate, and categorize. **Seedance** and **Doubao** are trademarks "
            "of ByteDance; this is an independent, community resource and is not "
            "affiliated with or endorsed by ByteDance."
        ),
        "prompt_label": "Prompt",
        "show_prompt": "Show full prompt",
        "try_on_tosea": "View on Tosea",
        "by_author": "by",
        "params": "Parameters",
        "template_badge": "starter template",
        "count_line": "{n} starter prompts across {k} categories",
        "cat_count": "{n} prompts",
    },
    "zh": {
        "lang_attr": "zh-CN",
        "tagline": "30 秒单镜直出 · 50 个全模态参考 · 局部级可控编辑。",
        "lang_self": "中文",
        "lang_alt": "English",
        "lang_alt_href": "README.md",
        "intro": (
            "为 **字节跳动 Seedance 2.5** 整理的开源 prompt 合集 —— 这款豆包视频生成"
            "模型于 **2026 年 6 月 23 日**火山引擎 FORCE 原动力大会上亮相,预计 "
            "**7 月初**正式上线。Prompt 按使用场景分类:文生视频、图生视频、"
            "多参考一致性、局部编辑与运镜。"
        ),
        "status_head": "状态",
        "status_body": (
            "Seedance 2.5 当前处于预览(企业内测),**尚未公开上线**。本仓库提前开张,"
            "为的是模型上线当天社区就有一个 Seedance 2.5 prompt 的归处。下列条目是"
            "作者撰写的**起手模板**,用于演示有效的 prompt 结构 —— 均已明确标注、"
            "不含任何虚构产出;待公开版上线后,会陆续加入社区贡献、带真实产出验证的 "
            "prompt。想一起共建?见[贡献指南](#贡献指南)。"
        ),
        "about_head": "什么是 Seedance 2.5?",
        "about_body": (
            "Seedance 2.5 是字节跳动新一代视频模型。据 FORCE 主题演讲,三项核心升级:\n\n"
            "- **30 秒单镜直出** —— 一段连续镜头直接生成(2.0 为 15 秒),叙事无需拼接。\n"
            "- **最多 50 个全模态参考** —— 图像、视频、文字在一次联合生成中组合"
            "(2.0 为 12 个),用于跨镜头的角色与品牌一致性。\n"
            "- **更可控的编辑** —— 局部级编辑(替换主体而不改动动作、机位与灯光),"
            "外加 3D 白模预演。\n\n"
            f"完整解析与横向对比,见我们的 [Seedance 2.5 指南]({BLOG_URL})。"
        ),
        "toc_head": "目录",
        "contributing_head": "贡献指南",
        "contributing_body": (
            "欢迎贡献 prompt。**请只修改 `prompts.json`** —— README 由 "
            "`scripts/build_readmes.py` 自动生成,手动改会在合并时被覆盖。公开版上线后,"
            "请附上产出视频/GIF 并署名 prompt 作者。数据结构见 "
            "[CONTRIBUTING.md](CONTRIBUTING.md)。"
        ),
        "license_head": "许可协议",
        "license_body": (
            "本合集采用 [CC BY 4.0](LICENSE) 协议。每条 prompt 的著作权归原作者所有,"
            "本仓库仅负责整理、翻译与分类。**Seedance**、**豆包(Doubao)** 为字节跳动"
            "商标;本项目为独立的社区资源,与字节跳动无隶属或背书关系。"
        ),
        "prompt_label": "Prompt",
        "show_prompt": "展开完整 prompt",
        "try_on_tosea": "在 Tosea 浏览",
        "by_author": "作者",
        "params": "参数",
        "template_badge": "起手模板",
        "count_line": "共 {n} 条起手 prompt,覆盖 {k} 个分类",
        "cat_count": "{n} 条",
    },
}


def slug_anchor(label: str) -> str:
    # GitHub heading slug: lowercase, drop punctuation (keep alnum/space/hyphen),
    # then spaces -> hyphens (no collapsing). "Camera & Cinematic" -> camera--cinematic
    s = "".join(c for c in label.strip().lower() if c.isalnum() or c in " -")
    return s.replace(" ", "-").strip("-")


def render_entry(s: dict, lang: str, e: dict, n: int) -> str:
    title = e["title"][lang]
    author = e["author"]["displayName"]
    p = e.get("parameters", {})
    pstr = " · ".join(
        f"{k}: {v}" for k, v in (
            ("duration", p.get("duration")),
            ("aspect", p.get("aspectRatio")),
            ("refs", p.get("references")),
        ) if v is not None
    )
    out = []
    out.append(f'### {n:02d}. {title}')
    out.append("")
    badge = f'`{s["template_badge"]}`' if e.get("promptType") == "template" else ""
    out.append(f'*{s["by_author"]} **{author}*** · {badge}'.rstrip(" ·"))
    out.append("")
    out.append(f'<a id="{e["id"]}"></a>')
    out.append("")
    out.append(e["description"][lang])
    out.append("")
    out.append("<details>")
    out.append(f'<summary><b>{s["prompt_label"]}</b> — {s["show_prompt"]}</summary>')
    out.append("")
    out.append(f'<blockquote>{html.escape(e["prompt"].strip())}</blockquote>')
    out.append("")
    out.append("</details>")
    out.append("")
    if pstr:
        out.append(f'**{s["params"]}:** {pstr}')
        out.append("")
    out.append(f'**[→ {s["try_on_tosea"]}]({e["toseaUrl"]})**')
    out.append("")
    out.append("---")
    out.append("")
    return "\n".join(out)


def render(lang: str, data: dict) -> str:
    s = STR[lang]
    labels = CATEGORY_LABELS[lang]
    entries = data["entries"]
    buckets: dict[str, list[dict]] = {}
    for e in entries:
        buckets.setdefault(e["category"], []).append(e)
    ordered = [c for c in CATEGORY_ORDER if buckets.get(c)]

    o = []
    o.append('<h1 align="center">Awesome Seedance 2.5 Prompts</h1>')
    o.append("")
    o.append(f'<p align="center"><i>{s["tagline"]}</i></p>')
    o.append("")
    o.append('<p align="center">')
    o.append('  <a href="LICENSE"><img alt="License: CC BY 4.0" src="https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg"></a>')
    o.append(f'  <a href="{TOSEA_PROMPTS_URL}"><img alt="Gallery on Tosea.ai" src="https://img.shields.io/badge/Gallery-Tosea.ai-000000?style=flat"></a>')
    o.append('  <img alt="Status: preview" src="https://img.shields.io/badge/Seedance%202.5-preview%20%C2%B7%20public%20launch%20July%202026-orange">')
    o.append(f'  <a href="{REPO_URL}/stargazers"><img alt="GitHub stars" src="https://img.shields.io/github/stars/ToseaAI/awesome-seedance-2.5-prompts?style=flat&color=yellow"></a>')
    o.append('</p>')
    o.append("")
    o.append(f'<p align="center"><b>{s["lang_self"]}</b> · <a href="{s["lang_alt_href"]}">{s["lang_alt"]}</a></p>')
    o.append("")
    o.append(s["intro"])
    o.append("")
    o.append(f'> **{s["status_head"]}** — {s["status_body"]}')
    o.append("")
    o.append(f'## {s["about_head"]}')
    o.append("")
    o.append(s["about_body"])
    o.append("")
    # TOC
    o.append(f'## {s["toc_head"]}')
    o.append("")
    for c in ordered:
        label = labels[c]
        o.append(f'- [{label}](#{slug_anchor(label)}) · *{s["cat_count"].format(n=len(buckets[c]))}*')
    o.append("")
    o.append(f'> {s["count_line"].format(n=len(entries), k=len(ordered))}. [→ {s["try_on_tosea"]}]({TOSEA_PROMPTS_URL})')
    o.append("")
    # categories
    for c in ordered:
        o.append(f'## {labels[c]}')
        o.append("")
        for i, e in enumerate(buckets[c], 1):
            o.append(render_entry(s, lang, e, i))
    # contributing + license
    o.append(f'## {s["contributing_head"]}')
    o.append("")
    o.append(s["contributing_body"])
    o.append("")
    o.append(f'## {s["license_head"]}')
    o.append("")
    o.append(s["license_body"])
    o.append("")
    m = data["model"]
    o.append(
        f'<p align="center"><sub>{m["name"]} · announced {m["releaseDate"]} at the '
        f'{m["announcedAt"]} · public launch {m["publicLaunch"]} · '
        f'Curated by <a href="{TOSEA_HOME_URL}">Tosea.ai</a> · '
        f'Auto-generated from <code>prompts.json</code>.</sub></p>'
    )
    o.append("")
    return "\n".join(o)


def main() -> None:
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    for lang, fn in (("en", "README.md"), ("zh", "README.zh-CN.md")):
        (ROOT / fn).write_text(render(lang, data), encoding="utf-8")
        print(f"wrote {fn} ({len(data['entries'])} entries)")


if __name__ == "__main__":
    main()
